### PR TITLE
Add basic filter

### PR DESCRIPTION
**Pull request by zeraye**
I implemented basic filter with options: "where", "when", "who" (you can see this in video). Currently search does nothing. When backend is be up, all components will be implemented with proper filters.

In this short video you can see, how this basic filter looks like:

https://github.com/flatly-pw/mobile-app/assets/53649257/02025662-50c3-4574-a881-eacc0cee2f79

### CODE REVIEW

**Comment by zeraye** [comment]
One important note: search-bar for destination isn't working currently. I will implement it today/tomorrow, and add to this pr (I forgot about it).

**Comment by kemeyr** [comment]
I think in the "when" filter it would be more intuitive to change the start date upon the third click. Now the only way to change the start day seems to be setting a very late end date and then clicking somewhere before it to reset.

**Comment by zeraye** [comment]
New calendar behavior @kemeyr 

https://github.com/flatly-pw/mobile-app/assets/53649257/22373ccb-d1ca-4bd3-87f3-49dfbd8fb2d9

**Comment by zeraye** [comment]
Destination search is implemented (also, like other components not connected with backend)

https://github.com/flatly-pw/mobile-app/assets/53649257/3dc287be-587f-4190-90be-7c9bf10311e5

**Review by kemeyr — APPROVED** [review]
Everything seems fine, approved

**Pull request merged**
